[CYB 15] Создать механику игры на canvas api
MYiLA/cyber-forest pull request #14
Opened 2023-06-24 20:50 UTC by MYiLA

2023-06-25 08:03 UTC, uncleBob193 requested changes
имена файлов в 
./src/pages/page-game/components/game/utils/
надо сделать в формате kebab-case

2023-06-26 21:53 UTC, uncleBob193 approved these changes

2023-06-27 20:15 UTC, Olegas requested changes
Задача: "Создать механику игры".
Я не увидел механику игры. 
Я увидел оформление - что и где расположено, рамочки, графика, картинки.
Но нет логики. Нельзя бросить кости, на кнопках нет действий и т.п.

Итого: не смотря на то, что к коду замечаний нет - принять работу не могу, т.к. я не увидел механику, увидел только оформление.

2023-06-27 20:15 UTC, Olegas commented on packages/client/src/pages/page-game/utils/create-dice.ts
> +import { v4 as uuid4 } from 'uuid'
Просто совет: если вдруг вам не нужно, что бы ваши идентификаторы были именно uuid-ами, а просто нужно что-то уникальное, можно взглянуть на [nanoid](https://www.npmjs.com/package/nanoid) - очень маленькая и быстра библиотека, умеющая генерировать случайные и уникальные идентификаторы

2023-06-27 20:15 UTC, Olegas commented on packages/client/src/pages/page-game/widgets/game/utils/draw-dices-sides.ts
> +      console.log(index)
Думаю это лишнее и просто осталось от отладки

2023-06-27 20:15 UTC, Olegas commented on packages/client/src/shared/ui/main-input/main-input.tsx
>    const DecorImage = useCallback(() => {
Как-то очень странно, что часть верстки обернули в useCallback. На мой взгляд уместнее было бы useMemo либо вынести в компонент

2023-06-27 20:22 UTC, Olegas requested changes
Задача: "Создать механику игры".
Я не увидел механику игры. 
Я увидел оформление - что и где расположено, рамочки, графика, картинки.
Но нет логики. Нельзя бросить кости, на кнопках нет действий и т.п.

Итого: не смотря на то, что к коду замечаний нет - принять работу не могу, т.к. я не увидел механику, увидел только оформление. Нужно реализовать минимальную механику игры - например обработку каких-то действий пользователя

2023-06-29 15:52 UTC, Olegas approved these changes

2023-06-29 17:59 UTC, merged