Feature/cyb 28 верстка страницы форума-лобби
MYiLA/cyber-forest pull request #31
Opened 2023-07-02 09:17 UTC by ValeriyaSudarikova

[CYB-28](https://linear.app/cyberforest/issue/CYB-28/vyorstka-stranicy-forumalobbi)

![image](https://github.com/MYiLA/cyber-forest/assets/100793154/c7ea268a-72f2-4300-b320-a55e6e11be8c)
![image](https://github.com/MYiLA/cyber-forest/assets/100793154/235944b7-3648-4584-96c6-16aabbc3bc6b)

1. Сделать роут для страницы форума (/lobby)

 2. Сверстать экраны форума: (экран "столов-игр", инф. о пользователе, создание стола, доступные топики, активный топик с комментариями)

2023-07-02 10:41 UTC, uncleBob193 approved these changes

2023-07-04 11:29 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/components/active-forum-topic/active-forum-topic.module.scss
> +  &.purple {
Css правила разделяем пустым абзацем, чтобы была читаемость
Прошу поправить во всём проекте аналогичные проблемы
Пример:
```
.list {
  display: flex;
  
  .item {
    color: red;
  }
}
```

2023-07-04 11:32 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/components/active-forum-topic/active-forum-topic.tsx
> +        className={`${styles.modal_wrapper} ${
Рекомендация: для подобных ситуация предлагаю воспользоваться classNames
https://www.npmjs.com/package/classnames
Пример: https://medium.com/2359media/why-react-classnames-is-a-lifesaver-and-how-you-should-use-it-if-you-arent-already-b25a44ed5603

2023-07-04 11:33 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/components/active-forum-topic/components/topic-comment/topic-comment.module.scss
> +  &_avatar {
Аналогично (пустой абзац)

2023-07-04 11:35 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/components/active-forum-topic/components/topic-comment/topic-comment.tsx
> +                    themeName === Theme.Purple
Предлагаю это сложный тернарник вынести в переменную
Для таких сложных случаев, предпочтительно использовать if / else (читабельнее)
Код пишем для других людей :), им так удобнее, дай слово :)

2023-07-04 11:36 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/components/active-forum-topic/components/topic-comment/topic-comment.tsx
> +              className={`${styles.comment_response} ${
Предлагаю всё-таки затащить classNames, о котором выше писал и затащить для таких случаев

2023-07-04 11:37 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/components/active-forum-topic/components/topic-comment/topic-comment.tsx
> +                const input = document.querySelectorAll(
Вынести в отдельную функцию, в инлайн колбеках такие манипуляции не делаем
Пример:
```
const handleClick = () => {body}

return (
  <div onClick={handleClick} />
)
```

2023-07-04 11:40 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/components/active-forum-topic/components/topic-subcomment/topic-subcomment.module.scss
> +  &_avatar {
Аналогичные проблемы с отступами

2023-07-04 11:40 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/components/active-forum-topic/components/topic-subcomment/topic-subcomment.tsx
> +          user?.avatar
Лучше вынести в переменную

2023-07-04 11:40 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/components/battle-settings/battle-settings.module.scss
> +    &.purpur {
Аналогичные проблемы

2023-07-04 11:41 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/components/battle-settings/battle-settings.tsx
> +const validators = {
Валидацию выносим в отдельные модуль, декомпозируем, импортируем
Плюсы:
Масштабируемость (можно будет переиспользовать ещё где-нибудь)

2023-07-04 11:42 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/components/forum-item/forum-item.module.scss
> +    &.neon {
Аналогично

2023-07-04 11:43 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/components/forum-item/forum-item.module.scss
> +}
Не хватает пустой строки в конце
https://translated.turbopages.org/proxy_u/en-ru.ru.8c8ea506-64a405ea-0d9f590e-74722d776562/https/stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file

2023-07-04 11:44 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/components/forum-item/forum-item.tsx
> +      // style={{height: last_message? last_message.content.length * 3 : 50}}
Предлагаю убрать закомментированные куски кода

2023-07-04 11:44 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/components/forum-item/forum-item.tsx
> +              last_message.user.avatar
В переменную

2023-07-04 11:44 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/components/forum-item/forum-item.tsx
> +          onClick ? onClick(id) : null
Предлагаю вынести в функцию и передавать на неё ссылку сюда

2023-07-04 11:45 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/components/rating/rating.module.scss
> +  &_title {
Аналогично

2023-07-04 11:45 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/components/rating/rating.module.scss
> +}
Нет пустой строки в конце файла

2023-07-04 11:45 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/components/rating/rating.tsx
> +        className={`${styles.rating_title} ${
classNames?)

2023-07-04 11:45 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/components/table-item/table-item.module.scss
> +  &_password {
Аналогично, поправить во всём PR

2023-07-04 11:46 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/components/table-item/table-item.tsx
> +  function getUsersImg(users: User[]) {
Можно подумать над оптимизацией с помощью useMemo
https://react.dev/reference/react/useMemo

2023-07-04 11:47 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/components/table-item/table-item.tsx
> +      {password ? (
В таких случаях, предпочтительно писать следующее:
{password && ( JSX )}

2023-07-04 11:47 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/page-lobby.module.scss
> +    &.neon {
Аналогично

2023-07-04 11:47 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/page-lobby.tsx
> +const tables_mock = [
Выносим моковые данные в отдельный модуль

2023-07-04 11:48 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/page-lobby.tsx
> +const forum_mock_topics: IChatData[] | [] = [
Аналогично

2023-07-04 11:48 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/page-lobby.tsx
> +  function OnSearchInput(value: string, array: IChatData[]) {
Функции с маленькой буквы

2023-07-04 11:49 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/page-lobby.tsx
> +        {topicList.map(topic => {
Необязательно писать c телом функции в { }, можно проще array.map(el => ( <Component {...el} /> )

2023-07-04 11:50 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/types.ts
> +export interface ITopicDetails {
Разделяем отступами типы

2023-07-04 11:50 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/types.ts
> +// interface IUserData {
Если не используется, то можно удалить

2023-07-04 11:50 UTC, IvanPeleshok commented on packages/client/src/shared/ui/checkbox/checkbox.module.scss
> +.input {
Аналогично

2023-07-04 11:51 UTC, IvanPeleshok commented on packages/client/src/shared/ui/checkbox/checkbox.module.scss
> +.input {
Аналогично

2023-07-04 11:51 UTC, IvanPeleshok commented on packages/client/src/shared/ui/checkbox/checkbox.tsx
> +        onChange={(event: ChangeEvent<HTMLInputElement>) => {
Достаточно предать ссылку на функцию, т.е
```
input onChange={onClick}
```

2023-07-04 11:52 UTC, IvanPeleshok commented on packages/client/src/shared/ui/switcher/switcher.module.scss
> +  &_label {
Аналогично (поправить во всём PR)

2023-07-04 11:53 UTC, IvanPeleshok commented on packages/client/src/shared/ui/switcher/switcher.tsx
> +    switch (active) {
Предлагаю переписать на if
```
useEffect(() => {
  active ? setActiveLabel(labels[1]) : setActiveLabel(labels[0])
}, [active])
```

2023-07-04 11:55 UTC, IvanPeleshok commented on packages/client/src/shared/ui/switcher/switcher.tsx
> +    active ? labels[0] : labels[1]
Достаточно странная конструкция с обращением к массиву по индексу (подумать, как можно идентифицировать их лучше, не по индексу)

2023-07-04 11:55 UTC, IvanPeleshok requested changes
Есть замечания

2023-07-05 09:28 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/components/active-forum-topic/components/topic-comment/topic-comment.tsx
> +              className={classNames(
Пример использования classNames:
```
className={classNames(styles.comment_response, {
  [styles.comment_response_purple]: themeName === Theme.Purple,
  [styles.comment_response_neon]: themeName !== Theme.Purple
})
```
Как по мне, такая запись кажется читаемее и её проще модифицировать при необходимости

2023-07-05 09:35 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/components/active-forum-topic/components/topic-comment/topic-comment.tsx
> +    const input = document.querySelectorAll(`input.${styles.comment_response}`)[
Если в дальнейшем работа с комментариями будет осуществляться через redux, то окей, как временное решение, но иначе необходимо подумать, как это можно изменить без обращения к DOM

2023-07-05 09:36 UTC, IvanPeleshok commented on packages/client/src/pages/page-lobby/components/active-forum-topic/components/topic-subcomment/topic-subcomment.tsx
> +  const UserAvatar = user?.avatar
переменные с маленькой буквы

2023-07-05 09:38 UTC, IvanPeleshok requested changes
Есть замечания

2023-07-06 08:33 UTC, IvanPeleshok approved these changes

2023-07-06 12:21 UTC, merged