[CYB-32] Реализовать одну из игровых механик, описанных в документе с логикой игры
MYiLA/cyber-forest pull request #38
Opened 2023-07-07 23:00 UTC by MYiLA

ЗАДАЧА В ДРАФТЕ, не мержить)

2023-07-10 22:13 UTC, ruslan4432013 approved these changes
Отличная и большая работа, круто!

2023-07-10 22:13 UTC, ruslan4432013 commented on packages/client/src/shared/utils/shuffle-array.ts
> +    result[j] = temp
Здесь можно было через [result[i], result[j]] = [result[j], result[i]]

2023-07-11 14:29 UTC, IvanPeleshok commented on packages/client/src/pages/page-game/widgets/forest/index.tsx
> +      return accessHireWarriors.find(access => access.type === currentCard.type)
Рекомендую выделить просто дополнительную переменную для таких целей
Читается попроще (код пишем для других разработчиков, поэтому это важно)

2023-07-11 14:32 UTC, IvanPeleshok commented on packages/client/src/pages/page-game/widgets/game/utils/draw-users-areas.ts
> +    const typeArea = area
Для чего добавлять переменную typeArea?
Предлагаю использовать area

2023-07-11 14:33 UTC, IvanPeleshok commented on packages/client/src/shared/utils/get-access-hire-warriors.ts
> +    if (type === DiceType.Cat)
Для читаемости предлагаю добавлять к if () фигурные скобки
Это будет проще читаться и выделять смысловую часть блока программы

2023-07-11 14:34 UTC, IvanPeleshok requested changes
Есть небольшие замечания

2023-07-11 21:14 UTC, IvanPeleshok commented on packages/client/src/pages/page-game/utils/get-next-player-type.ts
> +      if (playersCount === 2) {
return playersCount === 2 ? PlayerType.Red : PlayerType.Yellow
И ниже
(Является рекомендацией)

2023-07-11 21:16 UTC, IvanPeleshok commented on packages/client/src/shared/utils/shuffle-array.ts
> +    ;[result[i], result[j]] = [result[j], result[i]]
Такое ощущние, что ";" лишние

2023-07-11 21:16 UTC, IvanPeleshok approved these changes
Всё гуд, оставил незначительные рекомендации

2023-07-11 21:22 UTC, merged