[CYB-34] Проработать визуальную часть игры
MYiLA/cyber-forest pull request #48
Opened 2023-07-15 11:57 UTC by ruslan4432013

2023-07-15 12:09 UTC, MYiLA approved these changes

2023-07-15 12:09 UTC, MYiLA commented on packages/client/src/pages/page-game/widgets/game/utils/draw-dices-sides.ts
> +    // drawDiceSide({ ctx, diceSide, x: minX, y: minY })
Задокументированный код либо удаляем, либо пишем TODO: как планируется использовать или исправлять

2023-07-15 21:50 UTC, IvanPeleshok commented on packages/client/src/pages/page-game/widgets/game/utils/animation/dice-animation.ts
> +const allSides: DiceSide[] = [
Вынести в отдельный модуль (файл)
Максимально декомпозируем

2023-07-15 21:50 UTC, IvanPeleshok commented on packages/client/src/pages/page-game/widgets/game/utils/animation/dice-animation.ts
> +//
Лишний коммент

2023-07-15 21:54 UTC, IvanPeleshok commented on packages/client/src/pages/page-game/widgets/game/utils/animation/dice-animation.ts
> +  } else {
Предлагаю структуру кода оставлять линейной, без ветвлений
```
if () {
  ...
  
  return
}

// else
```

2023-07-15 21:56 UTC, IvanPeleshok commented on packages/client/src/pages/page-game/widgets/game/utils/draw-dice-side.ts
> +  if (isEnergyDiceSide(diceSide)) {
Аналогично
```
if () {
  return
}

if () {
  return
}

```

2023-07-15 21:58 UTC, IvanPeleshok commented on packages/client/src/pages/page-game/widgets/game/utils/drawers/energy-svg.ts
> +export const energySvg = `
Предлагаю вынести в отдельный модуль (файл)

2023-07-15 21:58 UTC, IvanPeleshok commented on packages/client/src/pages/page-game/widgets/game/utils/drawers/energy-svg.ts
> +export function parseSVGStringToHTMLElement(
Унести в общие хелперы (выглядит так, что может быть переиспользована)

2023-07-15 21:58 UTC, IvanPeleshok commented on packages/client/src/pages/page-game/widgets/game/utils/drawers/energy-svg.ts
> +export async function getImageFromSvg(svgElement: SVGElement) {
Аналогично

2023-07-15 21:59 UTC, IvanPeleshok requested changes
Есть небольшие замечания

2023-07-16 09:57 UTC, IvanPeleshok commented on packages/client/src/pages/page-game/widgets/game/utils/clear-context.ts
> +    ;[AreaType.Rest, AreaType.Preparation, AreaType.Attack].forEach(
";" видимо лишнее

2023-07-16 09:58 UTC, IvanPeleshok approved these changes

2023-07-16 13:28 UTC, merged