[CYB-44] Добавить ещё одно WEB API
MYiLA/cyber-forest pull request #69
Opened 2023-07-28 12:54 UTC by alexTaraskina

https://linear.app/cyberforest/issue/CYB-44/dobavit-eshyo-odno-web-api-krome-canvas-fetch

![image](https://github.com/MYiLA/cyber-forest/assets/20871455/81cc6689-66cc-4ef9-bc0b-db79d3a340eb)

Перед первым уведомлением появляется диалоговое окно с запросом на разрешение уведомлений. 
Отображение зависит от ОС и браузера. Есть ограничение на длину текста, поэтому некоторые сообщения пришлось сократить.

2023-07-28 13:15 UTC, uncleBob193 requested changes

2023-07-28 19:39 UTC, alexTaraskina commented on packages/client/src/shared/utils/notification.ts
@mrNote23 поправила

2023-07-28 20:07 UTC, uncleBob193 approved these changes

2023-07-31 21:57 UTC, IvanPeleshok commented on packages/client/src/shared/utils/notification.ts
> +  if (!("Notification" in window)) {
Рекомендация: для того, чтобы код бы максимально плоским и читаемым:
пробуем максимально отказаться от ветвления и воспользоваться следующей конструкцией:
```
if () {
  ...
  return
}

// else
```

2023-07-31 21:59 UTC, IvanPeleshok approved these changes
Хорошая работа
Апрув

2023-07-31 22:00 UTC, IvanPeleshok commented on packages/client/src/shared/utils/notification.ts
> +    Notification.requestPermission().then((permission) => {
Рекомендация: пользоваться последним синтаксисом языка, обработку асинхронной логики имплементируем с помощью async / await + try / catch
https://learn.javascript.ru/async-await

2023-08-02 11:47 UTC, merged