[CYB-41] добавление Oauth авторизации
MYiLA/cyber-forest pull request #75
Opened 2023-08-01 18:52 UTC by ValeriyaSudarikova

[Добавить OAuth-авторизацию в проект](https://linear.app/cyberforest/issue/CYB-42/dobavit-oauth-avtorizaciyu-v-proekt)

Ожидания:

Есть возможность авторизации через Yandex OAuth.

2023-08-01 19:12 UTC, uncleBob193 approved these changes

2023-08-01 20:43 UTC, IvanPeleshok commented on packages/client/src/core/api/auth-api.ts
> +    return this._axios
Предлагаю переписать на async / await + try / catch (и все места в рамках PR, где обработка промиса происходит похожим образом. К примеру, ниже в методе userOauthLogin)

Преимуществом такого подхода является плоский код, который очень удобно читать
Так же избавляет от ада вызовов колбеков и т.д

2023-08-01 20:44 UTC, IvanPeleshok commented on packages/client/src/core/api/auth-api.ts
> +    return this._axios
async / await + try / catch

2023-08-01 20:44 UTC, IvanPeleshok commented on packages/client/src/core/store/reducers/user-reducer.ts
> +  ApiAuth.userOauthLogin(code).then(() => ApiAuth.userGetInfo())
async / await + try / catch

2023-08-01 20:52 UTC, IvanPeleshok commented on packages/client/src/core/store/reducers/user-reducer.ts
> +        if (typeof localStorage !== "undefined") {
localStorage - объект в среде браузера, проверка на undefined, имхо, не нужна
Достаточно на само наличие проверить, т.е if (localStorage)
Поправь, если ошибаюсь

2023-08-01 20:53 UTC, IvanPeleshok commented on packages/client/src/core/store/reducers/user-reducer.ts
> +        console.log(action, "get info");
Отладочный код точно нужен?

2023-08-01 20:53 UTC, IvanPeleshok commented on packages/client/src/pages/page-home/page-home.tsx
> +        href={`${OAUTH_URL}${
Предлагаю вынести в переменную и сюда её передавать, так будет немного прозрачнее

2023-08-01 21:00 UTC, IvanPeleshok requested changes
Работа проделана огромная:

Отдельно хотелось бы выделить, что было классно:
* Отлично, что нет EOF ошибок в гите
* Декомпозированы модули
* Форматирование файлов радует

Отдельно хотелось бы обратить внимание на то, что можно улучшить:
* Ответы от сервера незатипизированы
* Используется then / catch для обработки промисов

2023-08-02 10:42 UTC, ValeriyaSudarikova commented on packages/client/src/core/api/auth-api.ts
> +    return this._axios
Привет @IvanPeleshok! 
У нас во врем проекте используется такая конструкция, 

`ApiAuth.userLogin(data).then(() => ApiAuth.userGetInfo())
`

кажется, эта запись более лаконичная и "плоская" чем следующая конструкция

```
try {
    await ApiAuth.userOauthLogin(code)
    await ApiAuth.userGetInfo()
  } catch (error) {
    rejectWithValue(error.response.data)
  }
```
  
 Также async/await вроде как не избавляет от многократного вызова и может вести себя не так, как ожидается, придется использовать что-то вроде Promise.all и код расползется на строки. Скорее, это вопрос вкуса, так что не вижу смысла переписывать половину проекта (все апи, кроме форума, у нас уже привязаны)

2023-08-02 11:19 UTC, ValeriyaSudarikova commented on packages/client/src/core/store/reducers/user-reducer.ts
> +        if (typeof localStorage !== "undefined") {
ты прав, тут не нужен

2023-08-02 12:28 UTC, IvanPeleshok commented on packages/client/src/core/api/auth-api.ts
> +    return this._axios
Даже если оставлять то, как оно есть - необходимо обработать исключения, если запрос упадёт с кодом ошибки
Обрабатываются ли у вас каким-либо образом ошибки?

2023-08-02 12:35 UTC, IvanPeleshok requested changes
Есть вопросы по PR

2023-08-02 12:40 UTC, ValeriyaSudarikova commented on packages/client/src/core/api/auth-api.ts
> +    return this._axios
Состояния запросов обрабатываются в редьюсерах, пример: 
```
.addCase(userRegister.pending, (state, action) => (логика))
.addCase(userRegister.rejected, (state, action) =>(другая логика))
.addCase(userRegister.fulfield, (state, action) =>(третья логика))
```
если на мы ловим ошибку, она помещается в состояние (например user.error) и далее ошибка транслируется пользователю (где необходимо, например, при неудачной авторизации)

2023-08-02 13:13 UTC, ValeriyaSudarikova commented on packages/client/src/pages/page-home/page-home.tsx
> +        to={`${OAUTH_URL}${
Да, ссори 
поправила)

2023-08-02 15:58 UTC, IvanPeleshok approved these changes

2023-08-02 19:19 UTC, merged