[CYB-62] эмоджи(бэкенд)
MYiLA/cyber-forest pull request #78
Opened 2023-08-02 19:22 UTC by ruslan4432013

2023-08-02 19:56 UTC, uncleBob193 approved these changes

2023-08-03 15:45 UTC, Olegas requested changes
Добрый день.
Есть замечание к реализации - написал подробный комментарий.
Классно что сразу взяли идентификатор пользователя из авторизации, а не с клиента.

2023-08-03 15:45 UTC, Olegas commented on packages/server/src/features/forum/topic/topic-service.ts
> +        reacted: value.users.includes(userId) ? true : false,
Кажется тут достаточно самого includes без тернарника

2023-08-03 15:45 UTC, Olegas commented on packages/server/src/features/forum/topic/topic-service.ts
> +    ;(data as EmojiRow[]).forEach((item: EmojiRow) => {
; в начале строки не лишняя случаем?

2023-08-03 17:55 UTC, ruslan4432013 commented on packages/server/src/features/forum/emoji/emoji-service.ts
> +      return { reacted: true }
Каждый пользователь может либо поставить, либо снять реакцию на топик,
дублей быть не может, как и одновременных запросов от одного пользователя
3 индекса используются из соображений ускорения поиска по трем критериям в базе

2023-08-03 19:00 UTC, Olegas commented on packages/server/src/features/forum/emoji/emoji-service.ts
> +      return { reacted: true }
К сожалению это не так. Давай разберемся.
Ситуация 1: представь пользователя на плохом канале. Он нажимает на кнопку поставить эмодзи. Ничего не происходит (на самом деле у него просто тупит интернет), он нажимает еще раз, потом еще раз. Итого мы имеем три запроса от одного пользователя на одно и то же действие - тогл эмодзи. В каком порядке и в какой момент эти запросы долетят до сервера - никто не знает. Результат - в лучшем случае эмодзи поставлен. В худшем - в базе дубли

Ситуация 2: два человека из под одной учетки в один момент делают одно и то же действие. Результат - не предсказуем. В лучшем случае один затоглит другого и оба увидят "ничего", в худшем - дубли в базе.

Единственный выход тут - обеспечить защиту от дублей на уровне хранения. В распределенных системах нормально это можно достичь только уникальным индексом и ничем другим.

Еще один совет - получить более предсказуемую реакцию на конкурирующие запросы поможет другая архитектура API. Если сделать запрос не "сделай toggle этого эмодзи" а вместо этого "поставь эмодзи" и "сними эмодзи" то конкурирующие запросы уже не дадут такой путаницы. Если нам придет три запроса "поставь эмодзи" или "убери эмодзи" то в каком бы порядке и в каком количестве мы бы их не выполняли, мы получим один единственный результат - эмодзи установлен (или снят).

На тему трех индексов. Если вы ищете в запросе по трем полям одновременно, то вам не поможет три индекса. Нужен один. Только тогда база его может эффективно использовать. Более того, если у вас есть отбор по полям A, B (дай все эмодзи этого пользователя из этого топика) а еще есть отбор только по А (дай все эмодзи этого топика) то тут еще и порядок важен. Он должен быть A, B но никак не B, A. Во втором случае, при поиске только по А, база данных не сможет эффективно выбрать данные (ну то есть выбрать та сможет, а вот эффективно - нет).

2023-08-04 06:15 UTC, Olegas requested changes
Получилось что-то не то. Ты добавил новую колонку, а надо индекс на три колонки. Посмотри в документации https://sequelize.org/docs/v7/models/indexes/ там есть примеры, как делать индекс на несколько колонок.

2023-08-04 06:34 UTC, Olegas requested changes
Да, все так, только осталось не забыть признак уникальности. Укажи unique: true и будет правильно

2023-08-04 06:44 UTC, Olegas approved these changes
Ура!

2023-08-04 06:56 UTC, merged