[CYB-64]: добавление АПИ форума
MYiLA/cyber-forest pull request #81
Opened 2023-08-11 07:51 UTC by ValeriyaSudarikova

[CYB-64](https://linear.app/cyberforest/issue/CYB-64/podderzhat-api-foruma-na-kliente)

В проекте полностью реализована функциональность форума. Клиент может: 

- посмотреть все топики, 
- создать новый топик, 
- написать комментарий. 

Все изменения сохраняются в базу данных и доступны после перезагрузки страницы

дополнительно: 

- есть функция добавления реакций,
- можно отвечать на комментарии
- можно изменять содержание топика / удалить топик
- можно удалить комментарий или ответ на комментарий
- можно найти топик из всех доступных в БД

2023-08-11 12:17 UTC, uncleBob193 approved these changes

2023-08-12 13:29 UTC, Olegas requested changes
Добрый день.
Есть замечания по коду.
Написал подробно в комментариях.
Требуется доработка.

2023-08-12 13:29 UTC, Olegas commented on packages/client/src/pages/page-lobby/components/active-forum-topic/components/topic-comment/topic-comment.tsx
> +                  await toDeleteComment(topicId, id);
Для чего тут await? Ведь от полученного значения все равно ничего не зависит.

2023-08-12 13:29 UTC, Olegas commented on packages/client/src/pages/page-lobby/components/active-forum-topic/components/topic-comment/topic-comment.tsx
> +                  );
Тот же вопрос - зачем await?

2023-08-12 13:29 UTC, Olegas commented on packages/client/src/pages/page-lobby/components/active-forum-topic/components/topic-comment/topic-comment.tsx
> +              {(!replies || !replies[0]) && (
Вот эти все логические конструкции про replies и replies[0] - они по сути друг друга дублируют. У вас одно значение, которое влияет на все - hasReplies = replies && replies[0].
Если его вынести в переменную и использовать его или его отрицание - читаться будет проще и при рефакторинге меньше шансов накосячить

2023-08-12 13:29 UTC, Olegas commented on packages/client/src/pages/page-lobby/components/active-forum-topic/components/topic-input/topic-input.tsx
> +    rule: "/^.+$/\n",
Вот этот \n в конце выглядит странно. Он точно нужен? Потому что на пустоту нормально проверит /^.+$/
Или тут какой-то секрет есть?

2023-08-12 13:29 UTC, Olegas commented on packages/client/src/pages/page-lobby/components/active-forum-topic/components/topic-input/topic-input.tsx
> +          onChange={onChange as (e: BaseSyntheticEvent) => void}
Зачем нужен обработчик, который ничего не делает?

2023-08-12 13:29 UTC, Olegas commented on packages/client/src/pages/page-lobby/components/active-forum-topic/components/topic-input/topic-input.tsx
> +          onBlur={onBlur as (e: BaseSyntheticEvent) => void}
Еще два пустых обработчика

2023-08-12 13:29 UTC, Olegas commented on packages/client/src/pages/page-lobby/components/active-forum-topic/components/topic-input/topic-input.tsx
> +            const input: HTMLInputElement | null = returnInput();
А зачем так хитро? Почему не через ref?

2023-08-12 13:29 UTC, Olegas commented on packages/client/src/pages/page-lobby/components/forum-item/forum-item.tsx
> +        }
А зачем проверять что тэг это div? Если вам нужно отличить от кликов на button ниже то лучше в тех обработчиках использовать stopPropagation

2023-08-12 13:29 UTC, Olegas commented on packages/client/src/pages/page-lobby/components/new-topic-form/new-topic-form.tsx
> +            onBlur={onBlur as (e: BaseSyntheticEvent) => void}
Снова куча пустых обработчиков. Зачем?

2023-08-12 13:29 UTC, Olegas commented on packages/client/src/pages/page-lobby/page-lobby.tsx
> +      setTopicList(forum);
А для чего нужно переносить на стейт компонента данные из стейта приложения? Почему нельзя просто forum использовать?

2023-08-12 13:29 UTC, Olegas commented on packages/client/src/shared/hooks/use-forum.ts
> +      await forumApi.addTopic(data);
Почему тут оказалась работа с API? У вас для других действий работа с API убрана в thunk-и, почему тут не так? Сделать бы async thunk, в нем сходить в добавление топика, дождаться и там же задиспатчить обновление топиков.
А так получается что работа с API размазана по коду

2023-08-12 13:29 UTC, Olegas commented on packages/client/src/shared/hooks/use-forum.ts
> +  const toAddReaction = useCallback(
Еще немного сбивают с толку названия, начинающиеся на to. To это "к". toAddReaction я читаю как "перейти к добавлению реакции", думаю что тут внутри навигация, смена URL, а тут оказывается работа с API

2023-08-12 13:29 UTC, Olegas commented on packages/client/src/pages/page-lobby/page-lobby.tsx
> +    if (activeTopicData) {
Зачем делать промежуточный стейт и эффект к нему? Почему в точке, где вы этот стейт меняете, сразу не позвать toChooseActiveTopic?

2023-08-12 13:29 UTC, Olegas commented on packages/client/src/shared/ui/loading/loading.tsx
> +      }}
Часть стилей лежат в файле со стилями, часть в коде. Зачем так? Надо сделать единообразно.

2023-08-12 13:29 UTC, Olegas commented on packages/client/src/shared/utils/date-formatter.ts
> +};
Посмотри на функцию Date#toLocaleString - скорее всего для твоего вариант есть уже готовое решение https://www.w3schools.com/jsref/jsref_tolocalestring.asp

2023-08-14 11:21 UTC, ValeriyaSudarikova commented on packages/client/src/pages/page-lobby/components/active-forum-topic/components/topic-input/topic-input.tsx
> +          onChange={onChange as (e: BaseSyntheticEvent) => void}
почему ничего не делает? Обработчик импортируется из хука "useForm" (packages/client/src/shared/hooks/use-form.ts) там можно посмотреть, что он делает

2023-08-14 17:46 UTC, ValeriyaSudarikova commented on packages/client/src/shared/hooks/use-forum.ts
> +  const toAddReaction = useCallback(
тут скорее используются в качетсве инфинитивных конструкций, типо "добавить" реакцию, используется во всем проекте, не вижу смысла переделывать все.

2023-08-14 18:30 UTC, ValeriyaSudarikova commented on packages/client/src/pages/page-lobby/components/new-topic-form/new-topic-form.tsx
> +            onBlur={onBlur as (e: BaseSyntheticEvent) => void}
ответила выше

2023-08-14 18:32 UTC, ValeriyaSudarikova commented on packages/client/src/pages/page-lobby/components/active-forum-topic/components/topic-comment/topic-comment.tsx
> +                  await toDeleteComment(topicId, id);
Предполагается, для навешивания доп. логики. Но пока ее нет - можно убрать

2023-08-15 09:12 UTC, Olegas commented on packages/client/src/pages/page-lobby/components/active-forum-topic/components/topic-input/topic-input.tsx
> +          onChange={onChange as (e: BaseSyntheticEvent) => void}
Тут я ошибся, сбило с толку => void в описании типа. Тут все хорошо

2023-08-15 09:16 UTC, Olegas commented on packages/client/src/pages/page-lobby/components/active-forum-topic/components/topic-comment/topic-comment.tsx
> +                  await toDeleteComment(topicId, id);
Лучше не оставлять такие штуки "просто так на будущее". Когда появится потребность - тогда и добавить. Потому что оно все так или иначе не бесплатно, и занимает какие-то ресурсы, либо вычислительные либо память (создаются новые Promise и т.п.)

2023-08-15 09:32 UTC, Olegas requested changes
Что-то не то с валидацией в формах. Написал комментарий. Кажется оно вообще не работает.
Также не исправлено замечание про размазывание логики работы с API - часть в thunk, часть в useForum

2023-08-15 09:32 UTC, Olegas commented on packages/client/src/pages/page-lobby/components/new-topic-form/new-topic-form.tsx
> +    rule: "/^.{0,50}+$/\n",
С этой регуляркой что-то не так. Сперва {0, 50} а затем + - не ясно как это.
Ну и {0,50} говорит нам о том что 0 символов допустимо, а по смыслу вроде как не должны тут пропуска пустые строки
И \n в конце опять какая-то странная. Как это работает?

И вообще, кажется эти правила на работают. Судя по коду [тут](https://github.com/MYiLA/cyber-forest/blob/5ebd2eb87fdd409f0509a728a48f59615a61bf21/packages/client/src/shared/hooks/use-form.ts) если rule это строка, то правило используется только в том случае, если rule матчится с /confirm:\S/. То есть эти вот правила они вообще не работают получается?

2023-08-15 17:18 UTC, ValeriyaSudarikova commented on packages/client/src/pages/page-lobby/components/new-topic-form/new-topic-form.tsx
> +    rule: "/^.{0,50}+$/\n",
Действительно, что-то начудила с формами. Поправила. И работу с АПИ, тоже)

2023-08-16 05:53 UTC, Olegas requested changes
Проверь пожалуйста все правила валидации. В них есть ошибки. Написал подробно комментарии к каждому месту, где увидел проблемы

2023-08-16 05:53 UTC, Olegas commented on packages/client/src/pages/page-lobby/page-lobby.tsx
> +      message: "в названии может быть до 40 символов",
Текст про 40 символов, проверка про 50

2023-08-16 05:53 UTC, Olegas commented on packages/client/src/pages/page-lobby/components/active-forum-topic/components/topic-input/topic-input.tsx
> +    rule: "/^.+$/",
Тут осталась строка вместо RegExp

2023-08-16 05:53 UTC, Olegas commented on packages/client/src/pages/page-lobby/components/new-topic-form/new-topic-form.tsx
> +    rule: /^.{0,50}$/,
0 символов это будет пустой заголовок

2023-08-16 05:53 UTC, Olegas commented on packages/client/src/pages/page-lobby/components/new-topic-form/new-topic-form.tsx
> +    rule: /^.$/,
Эта регулярка сработает только для ровно одного символа

2023-08-16 20:01 UTC, Olegas approved these changes
Спасибо, работа прията

2023-08-17 00:40 UTC, merged